### ISSUE TITLE
Attached artifact not working as expected

### ISSUE THREAD

**Issue by EricOtick** [hazendaz/makeself-maven-plugin#107] opened 2022-10-14 16:34 UTC
I am using the plugin with the following config

```
            <plugin>
                <groupId>com.github.hazendaz.maven</groupId>
                <artifactId>makeself-maven-plugin</artifactId>
                <version>${makeself-maven-plugin.version}</version>
                <executions>

                    <execution>
                        <id>dbbackup-makeself</id>
                        <goals>
                            <goal>makeself</goal>
                        </goals>
                        <configuration>
                            <archiveDir>${project.build.finalName}-dbbackup</archiveDir>
                            <fileName>dbbackup-${project.version}.run</fileName>
                            <label>dbbackup ${project.version} Self Extraction</label>
                            <startupScript>./install.sh</startupScript>
                        </configuration>
                    </execution>

                    <execution>
                        <id>pgdump-makeself</id>
                        <goals>
                            <goal>makeself</goal>
                        </goals>
                        <configuration>
                            <archiveDir>${project.build.finalName}-pgdump</archiveDir>
                            <fileName>pgdump-${project.version}.run</fileName>
                            <label>Pgdump ${project.version} Self Extraction</label>
                            <startupScript>./install.sh</startupScript>
                        </configuration>
                    </execution>

                    <execution>
                        <id>psql-makeself</id>
                        <goals>
                            <goal>makeself</goal>
                        </goals>
                        <configuration>
                            <archiveDir>${project.build.finalName}-psql</archiveDir>
                            <fileName>psql-${project.version}.run</fileName>
                            <label>Psql ${project.version} Self Extraction</label>
                            <startupScript>./install.sh</startupScript>
                        </configuration>
                    </execution>

                    <execution>
                        <id>shell-makeself</id>
                        <goals>
                            <goal>makeself</goal>
                        </goals>
                        <configuration>
                            <archiveDir>${project.build.finalName}-shell</archiveDir>
                            <fileName>barbs-shell-${project.version}.run</fileName>
                            <label>Barbs-shell ${project.version} Self Extraction</label>
                            <startupScript>./install.sh</startupScript>
                        </configuration>
                    </execution>

                </executions>
            </plugin>
```

Everything builds as expected except the attached artifacts are all the same.

```
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ barbs-server ---
[INFO] Installing /home/devroot/project/BARBS/barbs/barbs-server/pom.xml to /repository/project/barbs/barbs-server/0.10/barbs-server-0.10.pom
[INFO] Installing /home/devroot/project/BARBS/barbs/barbs-server/target/dbbackup-0.10.run to /repository/project/barbs/barbs-server/0.10/barbs-server-0.10.sh
[INFO] Installing /home/devroot/project/BARBS/barbs/barbs-server/target/pgdump-0.10.run to /repository/project/barbs/barbs-server/0.10/barbs-server-0.10.sh
[INFO] Installing /home/devroot/project/BARBS/barbs/barbs-server/target/psql-0.10.run to /repository/project/barbs/barbs-server/0.10/barbs-server-0.10.sh
[INFO] Installing /home/devroot/project/BARBS/barbs/barbs-server/target/barbs-shell-0.10.run to /repository/project/barbs/barbs-server/0.10/barbs-server-0.10.sh
```

I've looked at the Mojo source and it looks, at least to me, that the call is correct.

```
        // Attach artifact to maven build for install/deploy/release on success
        if (status == 0 && attach) {
            projectHelper.attachArtifact(project, "sh", new File(buildTarget, FilenameUtils.getName(fileName)));
        }
```

Certainly the source of the artifact is correct as it corresponds to the fileName parameter but the destination is always the same which results in only the last one being saved, albeit with the wrong filename.

As an idea, maybe use the alternate method

```void attachArtifact( MavenProject project, String artifactType, String artifactClassifier, File artifactFile );``` 

with a null artifact type and a classifier which can be configured and defaults to 'run'.

I have also tried this with a single execution and it is still wrong.

**Comment by hazendaz** [comment] 2022-10-15 02:39
@EricOtick Thanks for the report.  I can see how this can be problematic.  I'll try to look at this later this weekend and if easy enough will get a fix out shortly after.  Seems easy to repeat and makes sense given the type will only be once in current model.

I am pretty sure based on where it stores the artifact that its based off your pom name not the fileName from the configuration here but adding a classifier will help on that.  I'm thinking classifier would be the fileName, does that seem appropriate?

**Comment by EricOtick** [comment] 2022-10-15 07:52
I'm on the road today so I can't have a play but I think there is a bug in the call
```
projectHelper.attachArtifact(project, "sh", new File(buildTarget, FilenameUtils.getName(fileName)));
```
whereby the second parameter is really the packaging i.e. pom, jar etc. I think if you make this null it should work. The fact that the source and targets of the artifacts are different suggest something isn't quite as it should be.

If you take something like the assembly plugin you just need to specify the name and the process takes care of adding the version and ending. So a configuration of 
```
<version>0.10</version>
...
<configuration>
    <archiveDir>${project.build.finalName}-dbbackup</archiveDir>
    <fileName>dbbackup</fileName>
    <label>dbbackup ${project.version} Self Extraction</label>
    <startupScript>./install.sh</startupScript>
</configuration>
````
would result in an artifact ``dbbackup-0.10.run`` and you could specify the classifier but it defaults to ``run``.

**Comment by EricOtick** [comment] 2022-10-15 08:01
I've just realised my 'extension' will probably break existing use. Instead, have a configuration parameter ``fileRoot`` which does as suggested but can be overridden by ``fileName``. Actually, if there is a bug and it's fixed, this will break things as well.

**Comment by EricOtick** [comment] 2022-10-16 12:01
I've now had the chance to look at the source and it seems there isn't an artifact handler for an ``sh`` so it defaults to using one for a ``jar`` and hence create the artifact as ``${project.name}-${project.version}.artifact``.

I think just change the second parameter in
```
projectHelper.attachArtifact(project, "sh", new File(buildTarget, FilenameUtils.getName(fileName)));
```
from ``"sh"`` to ``null`` and it wil works as you originally expected. This will work for me and you can decide if and how you might want to code an extension.

**Comment by hazendaz** [comment] 2022-10-16 17:06
@EricOtick The behavior is expected.  Given this is to deploy along with a project artifact set, it would be inclined to be as defined by the pom itself.  The problem is two fold.  First, the usage I use entirely was for 'sh' and nothing more so that was hard coded.  I've exposed that on master now as 'extension' where you can now set that type such as 'run' in your case.  The second issue was that it did not classify the type thus always the same.  So I've also exposed 'classifier' which allows for that setup.  If you try master now you should be able to get all 4 properly attached.  Please give it a try and see if that does what you need.

**Comment by EricOtick** [comment] 2022-10-17 13:33
Took me a while to realise you deployed snapshots to sonatype.

I don't think it's quite right at the moment but it doesn't overwrite the installed artifacts which is good.

If you look at the maven way of doing things you have artifacts which start in the project directories and end up being installed or deployed. There are 2 main patterns; special artifacts and the rest. For now I'm only using a POM as special and assuming 

- artifact = my-project
- project.version = 1.2

in which case you will have files such as

| File in project directory | Installed artifact |
| --- | --- |
| pom.xml |my-project-1.2.pom |
| target/my-project-1.2.jar | my-project-1.2.jar |
| target/my-project-1.2-sources.jar | my-project-1.2-sources.jar |
| target/my-project-1.2-testdata.tar.gz | my-project-1.2-testdata.tar.gz  |

The last example is one using the assembly plugin where the classifier is set from the id of the assembly but note, without the version information but also with the artifact name prepended. My point is that the maven way is to take the basic information and then create a suitable filename.

One other thing to consider, the ability to extract the artifacts from /target before installing is important and should be possible without changing the file names.

My two penn'orth would suggest that a configuration of 
```
 <configuration>
    <archiveDir>${project.build.finalName}-psql</archiveDir>
    <classifier>psql</classifier>
</configuration>
```
would result in an artifact  ``${project.artifactId}-${project.version}-psql.sh`` in the repository but also in /target but currently in /target it is just makeself. This isn't the norm in maven and means I can't use the file from /target for testing easily.

If I change the configuration to
```
 <configuration>
    <archiveDir>${project.build.finalName}-psql</archiveDir>
    <classifier>psql</classifier>
   <fileName>psql</fileName>
</configuration>
```
The result is the same except the file in /target is psql.

If I change the configuration to
```
 <configuration>
    <archiveDir>${project.build.finalName}-psql</archiveDir>
    <classifier>psql</classifier>
    <fileName>${project.artifactId}-${project.version}-psql.sh</fileName>
</configuration>
```
It works as I would expect for maven but there seems to be more configuration than is needed and normally used in other similar plugins.

Ideally I would expect a configuration of
```
 <configuration>
    <classifier>psql</classifier>
</configuration>
```
To do as before with an archiveDir of ``${project.build.finalName}-<classifier>`` and an artifact name of ``${project.artifactId}-${project.version}-<classifier>.sh`` both in /target and the repository.

Maven is, after all, opinionated for a reason :wink:.

**Comment by hazendaz** [comment] 2022-10-17 15:12
fileName in this context is not for maven.  makeself requires fileName.  sounds like you are wanting the setup to converge and by extension of maven standards apply to makeself.  That was never the original intent and would likely be a rather breaking change.  I'm not sure what you mean by the contents of 'target' are not usable.  Whatever you told it to build should be there.  The m2 usage was an edge case to deploy the entire thing to sonatype/artifactory and expected 1 and only 1 to exist.  I think based on what you state, yes all 4 show up now in .m2 which improves things but you are looking for a bit more.

Could you do this for me, can you build a sample project tied to this version we can work from to look and see how to improve?  Main thing is to try to retain backwards compatibility so it doesn't break existing usage.  Cannot speak for all users but at least where I've designed this for my day job, I have a couple hundred running now and don't want to impact those in their current usage.  I do agree simplifying this makes sense as a general rule :)

**Comment by EricOtick** [comment] 2022-10-17 16:10
I'm happy to help and I'll build a project we can play with. I'm coming to the end of my working day and I'll be on site tomorrow but I'll get back to it on Wednesday.

Really, the plugin now works for me and does everything I need. I just think it's not following the maven way of doing as little as possible to make it work. 

I wouldn't say I want to impose maven standards on makeself but we are discussing a maven plugin and I expect, as I did, other users might be confused as it doesn't follow the normal pattern. I agree we don't want to break things and I'm sure we can achieve that.

I do think that a configuration which can overwrite files without warning has to be regarded as a bug and that behaviour is still apparent in the /target output.

**Comment by EricOtick** [comment] 2022-10-23 15:14
Okay, I'm back on this. I've created a noddy repo [makeself-plugin-tester](https://github.com/EricOtick/makeself-plugin-tester) to allow us to play with the plugin.

In this first test I've created a single execution that should use the configuration defaults. Currently the plugin makes an assumption that some other plugin has created the ``target`` directory so it fails. If you create the directory manually it still fails but the execution is treated as a success which is not what I would expect.

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------------< play:makeself >----------------------------
[INFO] Building makeself 0.1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- makeself-maven-plugin:1.5.0-SNAPSHOT:makeself (test-1) @ makeself ---
[INFO] GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
[INFO] Copyright (C) 2019 Free Software Foundation, Inc.
[INFO] License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
[INFO] 
[INFO] This is free software; you are free to change and redistribute it.
[INFO] There is NO WARRANTY, to the extent permitted by law.
[INFO] 
[INFO] Makeself version 2.4.6.snapshot.2022-07-09
[INFO] 
[INFO] Running makeself build
[INFO] Directory /home/eric/central/devroot/research/makeself/target/makeself does not exist.
[INFO] 
[ERROR] makeself failed with error status: 1
[INFO] bash: /home/eric/central/devroot/research/makeself/target/makeself: No such file or directory
[INFO] 
[ERROR] makeself failed with error status: 127
[INFO] bash: /home/eric/central/devroot/research/makeself/target/makeself: No such file or directory
[INFO] 
[ERROR] makeself failed with error status: 127
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ makeself ---
[INFO] Installing /home/eric/central/devroot/research/makeself/pom.xml to /home/eric/.m2/repository/play/makeself/0.1/makeself-0.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.850 s
[INFO] Finished at: 2022-10-23T16:10:41+01:00
[INFO] ------------------------------------------------------------------------

```

**Comment by hazendaz** [comment] 2022-10-23 16:41
You must tell it what to assemble.  There is nothing in your pom that does that.  In fact, there is nothing in you build and dummy sh file is in wrong folder space.  The entire premise of the plugin is that you are assembling something in target folder into makeself which is not present in your example.  It's fully expected that target exists as a result.  See the IT test.  It requires at least that much to do anything.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment] 2022-10-23 16:45
Should note this is not a plugin that is in replacement of assembly plugin.  It works off an assembly meaning most usage should typically run in verify to be controlled post assembly.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by EricOtick** [comment] 2022-10-23 17:12
I've now added a call to ``maven-resources-plugin`` which achieves the same. Now I get

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------------< play:makeself >----------------------------
[INFO] Building makeself 0.1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ makeself ---
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (resources) @ makeself ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- makeself-maven-plugin:1.5.0-SNAPSHOT:makeself (test-1) @ makeself ---
[INFO] GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
[INFO] Copyright (C) 2019 Free Software Foundation, Inc.
[INFO] License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
[INFO] 
[INFO] This is free software; you are free to change and redistribute it.
[INFO] There is NO WARRANTY, to the extent permitted by law.
[INFO] 
[INFO] Makeself version 2.4.6.snapshot.2022-07-09
[INFO] 
[INFO] Running makeself build
[INFO] Header is 714 lines long
[INFO] 
[INFO] About to compress 2 KB of data...
[INFO] Adding files to archive named "/home/eric/central/devroot/research/makeself/target/makeself"...
[INFO] ./makeself.sh
[INFO] ./testdata
[INFO] CRC: 871251095
[INFO] MD5: 4bc6595f7df25bc6f2595a70515d8a0d
[INFO] /home/eric/central/devroot/research/makeself/target/makeself-tmp/makeself-header.sh: line 1: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] /home/eric/central/devroot/research/makeself/target/makeself-tmp/makeself-header.sh: line 420: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] /home/eric/central/devroot/research/makeself/target/makeself-tmp/makeself-header.sh: line 421: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] 
[INFO] /home/eric/central/devroot/research/makeself/target/makeself-tmp/makeself.sh: line 814: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] Self-extractable archive "/home/eric/central/devroot/research/makeself/target/makeself" successfully created.
[INFO] 
[INFO] /home/eric/central/devroot/research/makeself/target/makeself: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] 
[ERROR] makeself failed with error status: 126
[INFO] /home/eric/central/devroot/research/makeself/target/makeself: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] 
[ERROR] makeself failed with error status: 126
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ makeself ---
[INFO] Installing /home/eric/central/devroot/research/makeself/pom.xml to /home/eric/.m2/repository/play/makeself/0.1/makeself-0.1.pom
[INFO] Installing /home/eric/central/devroot/research/makeself/target/makeself to /home/eric/.m2/repository/play/makeself/0.1/makeself-0.1.sh
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.547 s
[INFO] Finished at: 2022-10-23T18:11:25+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install (default-install) on project makeself: Failed to install artifact play:makeself:sh:0.1: /home/eric/central/devroot/research/makeself/target/makeself (Is a directory) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by hazendaz** [comment] 2022-10-23 20:07
Fix has been applied to master that ensures 'target' always exists.

**Comment by hazendaz** [comment] 2022-10-23 21:44
Fix is negated now, added in early validation instead of letting makeself do it as is done now.  Checks on archive directory existing and that script exists and is of right expected content with ./ starting.  Integration tests added for same.

**Comment by EricOtick** [comment] 2022-10-24 15:09
How far do you want me to go with this? I'm being critical of your work when you probably did it for your own benefit. The plugin works for me so no changes are needed and you wouldn't want to break your usage. I'm happy to continue if you want.

**Comment by hazendaz** [comment] 2022-10-24 20:10
@EricOtick Your fine :)  Tightened up those issues so it should start to react better or earlier before sending off to makeself to do verifications :)  So far these are good improvements and makes it a bit more clear on intent of plugin.

**Comment by EricOtick** [comment] 2022-10-25 10:40
Good. 

Using the current pom in my repo should apply the defaults and produce an artifact. It fails with the following output

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------------< play:makeself >----------------------------
[INFO] Building makeself 0.1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ makeself ---
[INFO] Deleting /home/eric/central/devroot/research/makeself/target
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (resources) @ makeself ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- makeself-maven-plugin:1.5.0-SNAPSHOT:makeself (test-1) @ makeself ---
[INFO] GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
[INFO] Copyright (C) 2019 Free Software Foundation, Inc.
[INFO] License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
[INFO] 
[INFO] This is free software; you are free to change and redistribute it.
[INFO] There is NO WARRANTY, to the extent permitted by law.
[INFO] 
[INFO] Makeself version 2.4.6.snapshot.2022-07-09
[INFO] 
[INFO] Running makeself build
[INFO] Header is 714 lines long
[INFO] 
[INFO] About to compress 2 KB of data...
[INFO] Adding files to archive named "/home/eric/central/devroot/research/makeself/target/makeself"...
[INFO] ./makeself.sh
[INFO] ./testdata
[INFO] CRC: 3210270665
[INFO] MD5: b77464537ec01dbb8903d607f85ea4a4
[INFO] /home/eric/central/devroot/research/makeself/target/makeself-tmp/makeself-header.sh: line 1: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] /home/eric/central/devroot/research/makeself/target/makeself-tmp/makeself-header.sh: line 420: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] /home/eric/central/devroot/research/makeself/target/makeself-tmp/makeself-header.sh: line 421: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] 
[INFO] /home/eric/central/devroot/research/makeself/target/makeself-tmp/makeself.sh: line 814: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] Self-extractable archive "/home/eric/central/devroot/research/makeself/target/makeself" successfully created.
[INFO] 
[INFO] /home/eric/central/devroot/research/makeself/target/makeself: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] 
[ERROR] makeself failed with error status: 126
[INFO] /home/eric/central/devroot/research/makeself/target/makeself: /home/eric/central/devroot/research/makeself/target/makeself: Is a directory
[INFO] 
[ERROR] makeself failed with error status: 126
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ makeself ---
[INFO] Installing /home/eric/central/devroot/research/makeself/pom.xml to /home/eric/.m2/repository/play/makeself/0.1/makeself-0.1.pom
[INFO] Installing /home/eric/central/devroot/research/makeself/target/makeself to /home/eric/.m2/repository/play/makeself/0.1/makeself-0.1.sh
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.449 s
[INFO] Finished at: 2022-10-25T11:10:01+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install (default-install) on project makeself: Failed to install artifact play:makeself:sh:0.1: /home/eric/central/devroot/research/makeself/target/makeself (Is a directory) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Running under debug the command to bash is 

```
[DEBUG] Execution commands: [bash, /home/eric/central/devroot/research/makeself/target/makeself-tmp/makeself.sh, /home/eric/central/devroot/research/makeself/target/makeself, /home/eric/central/devroot/research/makeself/target/makeself, Make self-extrabable archives, ./makeself.sh]
```

The output filename is the same as the archiveDir which can't be correct. It looks like the instruction ``target.add(buildTarget.concat(fileName));`` at line 543 in ``MakeselfMojo.java`` should have an extension added.

If I supply a filename which is different to the archiveDir, i.e. ``makeself.sh`` it works.

**Comment by hazendaz** [comment] 2022-10-25 12:37
fixed default file name to makeself.sh.  pushed to master now.

**Comment by hazendaz** [comment] 2022-10-27 13:13
label fixed.

not sure what you mean by more convention.  if regards to final name, that isn't a maven thing in this context, its 100% a makeself topic so that will continue to be the way it is.  Is there something else?

**Comment by EricOtick** [comment] 2022-10-28 16:18
No, I think that's it. We can use the plugin as we need it so nothing more is needed. Happy Days.

Are you going to release 1.5.0?

**Comment by hazendaz** [comment] 2022-10-28 20:14
I can release later this weekend.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment] 2022-10-30 14:40
1.5.0 has been released and will show up in central index in a few hours.

**Closed by hazendaz** 2022-10-30 14:40 UTC
Labels: enhancement

**Comment by EricOtick** [comment] 2022-10-31 14:59
Got it. Thanks for your efforts.

**Comment by hazendaz** [comment] 2022-11-01 01:01
It's out now

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
